
log_level: INFO
log_path: logs

server_host: 0.0.0.0
server_port: 8080

threads: 5

fps: 30
quality: 96
broadcast: false
left: 0
top: 0
width: 0
height: 0
resize_width: 0
resize_height: 0

tasks_queue_size: 1
buffer_queue_size: 0
images_queue_size: 0
convert_buffer_size: 1
convert_images_size: 1

to_sbs: false
cursor: false

shot: 1
alpha: 15
convert: 3
mode: sync-single-multi