
log_level: INFO
log_path: logs

server_host: 0.0.0.0
server_port: 1935

threads: 5

fps: 30

write_frames_timeout: 500

bit_rate: 64

full_screen: true

left: 0
top: 0
width: 0
height: 0
resize_width: 0
resize_height: 0

buffer_queue_size: 0

to_sbs: false
cursor: false

alpha: 15
convert: 4
mode: single
